// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson85e49415DecodeGithubComSanposhihoGomockhandlerModel(in *jlexer.Lexer, out *Chunk) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "mocks":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Mocks = make(map[string]*Mock)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 *Mock
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(Mock)
						}
						easyjson85e49415DecodeGithubComSanposhihoGomockhandlerModel1(in, v1)
					}
					(out.Mocks)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson85e49415EncodeGithubComSanposhihoGomockhandlerModel(out *jwriter.Writer, in Chunk) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"mocks\":"
		out.RawString(prefix[1:])
		if in.Mocks == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.Mocks {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				if v2Value == nil {
					out.RawString("null")
				} else {
					easyjson85e49415EncodeGithubComSanposhihoGomockhandlerModel1(out, *v2Value)
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Chunk) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson85e49415EncodeGithubComSanposhihoGomockhandlerModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Chunk) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson85e49415EncodeGithubComSanposhihoGomockhandlerModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Chunk) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson85e49415DecodeGithubComSanposhihoGomockhandlerModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Chunk) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson85e49415DecodeGithubComSanposhihoGomockhandlerModel(l, v)
}
func easyjson85e49415DecodeGithubComSanposhihoGomockhandlerModel1(in *jlexer.Lexer, out *Mock) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "source":
			out.Source = string(in.String())
		case "destination":
			out.Destination = string(in.String())
		case "checksum":
			if in.IsNull() {
				in.Skip()
			} else {
				copy(out.CheckSum[:], in.Bytes())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson85e49415EncodeGithubComSanposhihoGomockhandlerModel1(out *jwriter.Writer, in Mock) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"source\":"
		out.RawString(prefix[1:])
		out.String(string(in.Source))
	}
	{
		const prefix string = ",\"destination\":"
		out.RawString(prefix)
		out.String(string(in.Destination))
	}
	{
		const prefix string = ",\"checksum\":"
		out.RawString(prefix)
		out.Base64Bytes(in.CheckSum[:])
	}
	out.RawByte('}')
}
