// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	reflectmode "github.com/sanposhiho/gomockhandler/mockgen/reflectmode"
	sourcemode "github.com/sanposhiho/gomockhandler/mockgen/sourcemode"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6615c02eDecodeGithubComSanposhihoGomockhandlerModel(in *jlexer.Lexer, out *Config) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "mocks":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Mocks = make(map[string]*Mock)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 *Mock
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(Mock)
						}
						easyjson6615c02eDecodeGithubComSanposhihoGomockhandlerModel1(in, v1)
					}
					(out.Mocks)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6615c02eEncodeGithubComSanposhihoGomockhandlerModel(out *jwriter.Writer, in Config) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"mocks\":"
		out.RawString(prefix[1:])
		if in.Mocks == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.Mocks {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				if v2Value == nil {
					out.RawString("null")
				} else {
					easyjson6615c02eEncodeGithubComSanposhihoGomockhandlerModel1(out, *v2Value)
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Config) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6615c02eEncodeGithubComSanposhihoGomockhandlerModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Config) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6615c02eEncodeGithubComSanposhihoGomockhandlerModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Config) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6615c02eDecodeGithubComSanposhihoGomockhandlerModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Config) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6615c02eDecodeGithubComSanposhihoGomockhandlerModel(l, v)
}
func easyjson6615c02eDecodeGithubComSanposhihoGomockhandlerModel1(in *jlexer.Lexer, out *Mock) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "destination":
			out.Destination = string(in.String())
		case "checksum":
			if in.IsNull() {
				in.Skip()
			} else {
				copy(out.CheckSum[:], in.Bytes())
			}
		case "mode":
			out.Mode = mode(in.String())
		case "reflect_mode_runner":
			if in.IsNull() {
				in.Skip()
				out.ReflectModeRunner = nil
			} else {
				if out.ReflectModeRunner == nil {
					out.ReflectModeRunner = new(reflectmode.Runner)
				}
				easyjson6615c02eDecodeGithubComSanposhihoGomockhandlerMockgenReflectmode(in, out.ReflectModeRunner)
			}
		case "source_mode_runner":
			if in.IsNull() {
				in.Skip()
				out.SourceModeRunner = nil
			} else {
				if out.SourceModeRunner == nil {
					out.SourceModeRunner = new(sourcemode.Runner)
				}
				easyjson6615c02eDecodeGithubComSanposhihoGomockhandlerMockgenSourcemode(in, out.SourceModeRunner)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6615c02eEncodeGithubComSanposhihoGomockhandlerModel1(out *jwriter.Writer, in Mock) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"destination\":"
		out.RawString(prefix[1:])
		out.String(string(in.Destination))
	}
	{
		const prefix string = ",\"checksum\":"
		out.RawString(prefix)
		out.Base64Bytes(in.CheckSum[:])
	}
	{
		const prefix string = ",\"mode\":"
		out.RawString(prefix)
		out.String(string(in.Mode))
	}
	if in.ReflectModeRunner != nil {
		const prefix string = ",\"reflect_mode_runner\":"
		out.RawString(prefix)
		easyjson6615c02eEncodeGithubComSanposhihoGomockhandlerMockgenReflectmode(out, *in.ReflectModeRunner)
	}
	if in.SourceModeRunner != nil {
		const prefix string = ",\"source_mode_runner\":"
		out.RawString(prefix)
		easyjson6615c02eEncodeGithubComSanposhihoGomockhandlerMockgenSourcemode(out, *in.SourceModeRunner)
	}
	out.RawByte('}')
}
func easyjson6615c02eDecodeGithubComSanposhihoGomockhandlerMockgenSourcemode(in *jlexer.Lexer, out *sourcemode.Runner) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "source":
			out.Source = string(in.String())
		case "destination":
			out.Destination = string(in.String())
		case "package":
			out.Package = string(in.String())
		case "imports":
			out.Imports = string(in.String())
		case "aux_files":
			out.AuxFiles = string(in.String())
		case "mock_names":
			out.MockNames = string(in.String())
		case "self_package":
			out.SelfPackage = string(in.String())
		case "copyright_file":
			out.CopyrightFile = string(in.String())
		case "write_pkg_comment":
			out.WritePkgComment = bool(in.Bool())
		case "debug_parser":
			out.DebugParser = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6615c02eEncodeGithubComSanposhihoGomockhandlerMockgenSourcemode(out *jwriter.Writer, in sourcemode.Runner) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"source\":"
		out.RawString(prefix[1:])
		out.String(string(in.Source))
	}
	{
		const prefix string = ",\"destination\":"
		out.RawString(prefix)
		out.String(string(in.Destination))
	}
	{
		const prefix string = ",\"package\":"
		out.RawString(prefix)
		out.String(string(in.Package))
	}
	{
		const prefix string = ",\"imports\":"
		out.RawString(prefix)
		out.String(string(in.Imports))
	}
	{
		const prefix string = ",\"aux_files\":"
		out.RawString(prefix)
		out.String(string(in.AuxFiles))
	}
	{
		const prefix string = ",\"mock_names\":"
		out.RawString(prefix)
		out.String(string(in.MockNames))
	}
	{
		const prefix string = ",\"self_package\":"
		out.RawString(prefix)
		out.String(string(in.SelfPackage))
	}
	{
		const prefix string = ",\"copyright_file\":"
		out.RawString(prefix)
		out.String(string(in.CopyrightFile))
	}
	{
		const prefix string = ",\"write_pkg_comment\":"
		out.RawString(prefix)
		out.Bool(bool(in.WritePkgComment))
	}
	{
		const prefix string = ",\"debug_parser\":"
		out.RawString(prefix)
		out.Bool(bool(in.DebugParser))
	}
	out.RawByte('}')
}
func easyjson6615c02eDecodeGithubComSanposhihoGomockhandlerMockgenReflectmode(in *jlexer.Lexer, out *reflectmode.Runner) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "package_name":
			out.PackageName = string(in.String())
		case "interfaces":
			out.Interfaces = string(in.String())
		case "source":
			out.Source = string(in.String())
		case "destination":
			out.Destination = string(in.String())
		case "package":
			out.Package = string(in.String())
		case "imports":
			out.Imports = string(in.String())
		case "aux_files":
			out.AuxFiles = string(in.String())
		case "build_flags":
			out.BuildFlags = string(in.String())
		case "mock_names":
			out.MockNames = string(in.String())
		case "self_package":
			out.SelfPackage = string(in.String())
		case "copyright_file":
			out.CopyrightFile = string(in.String())
		case "exec_only":
			out.ExecOnly = string(in.String())
		case "prog_only":
			out.ProgOnly = bool(in.Bool())
		case "write_pkg_comment":
			out.WritePkgComment = bool(in.Bool())
		case "debug_parser":
			out.DebugParser = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6615c02eEncodeGithubComSanposhihoGomockhandlerMockgenReflectmode(out *jwriter.Writer, in reflectmode.Runner) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"package_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.PackageName))
	}
	{
		const prefix string = ",\"interfaces\":"
		out.RawString(prefix)
		out.String(string(in.Interfaces))
	}
	{
		const prefix string = ",\"source\":"
		out.RawString(prefix)
		out.String(string(in.Source))
	}
	{
		const prefix string = ",\"destination\":"
		out.RawString(prefix)
		out.String(string(in.Destination))
	}
	{
		const prefix string = ",\"package\":"
		out.RawString(prefix)
		out.String(string(in.Package))
	}
	{
		const prefix string = ",\"imports\":"
		out.RawString(prefix)
		out.String(string(in.Imports))
	}
	{
		const prefix string = ",\"aux_files\":"
		out.RawString(prefix)
		out.String(string(in.AuxFiles))
	}
	{
		const prefix string = ",\"build_flags\":"
		out.RawString(prefix)
		out.String(string(in.BuildFlags))
	}
	{
		const prefix string = ",\"mock_names\":"
		out.RawString(prefix)
		out.String(string(in.MockNames))
	}
	{
		const prefix string = ",\"self_package\":"
		out.RawString(prefix)
		out.String(string(in.SelfPackage))
	}
	{
		const prefix string = ",\"copyright_file\":"
		out.RawString(prefix)
		out.String(string(in.CopyrightFile))
	}
	{
		const prefix string = ",\"exec_only\":"
		out.RawString(prefix)
		out.String(string(in.ExecOnly))
	}
	{
		const prefix string = ",\"prog_only\":"
		out.RawString(prefix)
		out.Bool(bool(in.ProgOnly))
	}
	{
		const prefix string = ",\"write_pkg_comment\":"
		out.RawString(prefix)
		out.Bool(bool(in.WritePkgComment))
	}
	{
		const prefix string = ",\"debug_parser\":"
		out.RawString(prefix)
		out.Bool(bool(in.DebugParser))
	}
	out.RawByte('}')
}
